### ISSUE TITLE
TypeError: setting a property that has only a getter

### ISSUE THREAD

**Issue by ahmed-sherien** [ruionwriting/ngGuid#2]
when I call `Guid.newGuid();`
it gives this error:

```
TypeError: setting a property that has only a getter
window.crypto = window.crypto || window.msCrypto;
```

**Comment by ahmed-sherien** [comment]
@ruionwriting please update bower lib

**Comment by ruionwriting** [comment]
Tkx @ahmed-sherien I'll have a look later this week.

**Comment by ruionwriting** [comment]
I'm closing this as I've added new release.

**Comment by ahmed-sherien** [comment]
you missed the minified version ...

**Comment by ruionwriting** [comment]
#shame. I'll sort it out.

**Comment by ruionwriting** [comment]
Done. Replaced release 0.1.2. Thank you @ahmed-sherien.

**Comment by ahmed-sherien** [comment]
thanks
